BlogDjango/BlogDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace="default")),
    path('', include('blog.urls'))
]

BlogDjango/blog/urls.py
from django.urls import path
from . import views

app_name="blog"
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('register', views.MyRegistrationView.as_view(), name="register"),
    path('login', views.MyLoginView.as_view(), name="login"),
    path('logout', views.user_logout, name="logout"),
    path('users', views.UsersListView.as_view(), name="users"),
    path('profile/<str:username>/', views.ProfileDetailView.as_view(), name='profile'),
    path('profile/<str:username>/remove_friend', views.remove_friend, name='remove_friend'),
    path('profile/<str:username>/send_friend_invite', views.send_friend_invitation, name='send_friend_invitation'),
    path('profile/<str:username>/send_message', views.send_message, name='send_message'),
    path('profile/<str:username>/inbox/', views.InboxView.as_view(), name='inbox'),
    path('profile/inbox/delete_msg/<int:msg_pk>/', views.delete_msg, name='delete_msg'),
    path('profile/inbox/message/<str:username>/', views.accept_invitation, name='accept_invitation'),
]

BlogDjango/blog/models.py
from django.conf import settings
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Message(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_invitations')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_invitations')
    subject = models.TextField(max_length=100)
    body = models.TextField()
    seen = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message(from:{self.from_user.username} to:{self.to_user} id:{self.id})"

    def send(self):
        self.created_at = timezone.now()
        self.save()
        pass


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    friends = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return f"UserProfile({self.user.username})"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

BlogDjango/blog/forms.py
from django import forms
from .models import Post, UserProfile, Message
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class ProfileForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.SelectDateWidget(years=range(1900, 2025)))

    class Meta:
        model = UserProfile
        fields = ('birth_date', )


class SendMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('subject', 'body')

BlogDjango/blog/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from .models import Post, Message
from django.http import Http404
from .forms import PostForm, SendMessageForm, ProfileForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView


class MyLoginView(LoginView):
    template_name = 'blog/registration/login.html'
    authentication_form = AuthenticationForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        # Redirect to the user's profile page
        return reverse_lazy('blog:profile', kwargs={'username': self.request.user.username})


class MyRegistrationView(CreateView):
    template_name = 'blog/registration/register.html'
    form_class = UserCreationForm
    profile_form_class = ProfileForm  # Add the ProfileForm
    success_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_form'] = self.profile_form_class()  # Add the profile form to context
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        profile_form = self.profile_form_class(request.POST)
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            login(request, user)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

@login_required
def user_logout(request):
    logout(request)
    return redirect('blog:login')


@login_required
def delete_user(request):
    if request.method == 'POST':
        user = request.user
        user.delete()
        return redirect('login')
    return render(request, 'registration/delete.html')


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    fields = ['title', 'content', 'author']
    template_name = 'blog/post_detail.html'
    success_url = reverse_lazy('blog:post_list')

    def get_queryset(self):
        return Post.objects.filter(pk=self.kwargs['pk'])


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.publish()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if post.author != request.user:
        return HttpResponseForbidden()

    if request.method == "POST":
        post.delete()
        return redirect('blog:profile', username=request.user.username)
    else:
        print("tutaj!")
        return render(request, 'blog/registration/profile.html', {'post': post})


class UsersListView(ListView):
    model = User
    template_name = 'blog/registration/users.html'
    context_object_name = 'users_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        logged_in_user = self.request.user

        excluded_users = User.objects.filter(~Q(id=logged_in_user.id) & ~Q(is_superuser=True))

        context['users_list'] = excluded_users

        return context


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'blog/registration/profile.html'
    context_object_name = 'viewed_user'
    pk_url_kwarg = 'pk'

    def get_object(self, queryset=None):
        username = self.kwargs.get('username')
        return User.objects.get(username=username)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        viewed_user = self.get_object()
        # Check if the user is authenticated
        if self.request.user.is_authenticated:
            # If the viewed user is the logged-in user
            user_profile = viewed_user.userprofile
            friends = user_profile.friends.all()
            posts = Post.objects.filter(author=self.request.user)

            context['user_posts'] = posts
            context['user_friends'] = friends
            if viewed_user == self.request.user:

                context['logged_profile'] = True
            else:

                context['logged_profile'] = False
        else:
            context['message'] = "Please log in to view full profile."

        return context

    def dispatch(self, request, *args, **kwargs):
        """
        Override the dispatch method to handle admin redirection.
        """
        viewed_user = self.get_object()
        # Check if the viewed user is an admin
        if viewed_user.is_superuser:
            # Redirect to a specific page if the viewed user is an admin
            return redirect('blog:post_list')

        return super().dispatch(request, *args, **kwargs)


@login_required
def remove_friend(request, username):
    try:
        friend = User.objects.get(username=username)
        friend_profile = friend.userprofile
        user_profile = request.user.userprofile
    except User.DoesNotExist:
        raise Http404("User does not exist")

    if friend_profile is None or user_profile is None:
        raise Http404("User profile does not exist")

    if friend_profile not in user_profile.friends.all() or user_profile not in friend_profile.friends.all():
        raise Http404("Friend not found in user's friend list")

    friend_profile.friends.remove(user_profile)
    user_profile.friends.remove(friend_profile)

    return redirect('blog:profile', username=request.user.username)


class InboxView(ListView):
    template_name = 'blog/registration/inbox.html'
    context_object_name = 'messages'

    def get_queryset(self):
        user = self.request.user
        return Message.objects.filter(to_user=user)


@login_required
def accept_invitation(request, username):
    from_user = get_object_or_404(User,username=username)
    to_user = request.user

    if not from_user.userprofile.friends.filter(user=to_user).exists() and \
           not to_user.userprofile.friends.filter(user=from_user).exists():

       from_user.userprofile.friends.add(to_user.userprofile)
       to_user.userprofile.friends.add(from_user.userprofile)

    return redirect('blog:inbox', username=request.user.username)


@login_required
def delete_msg(request, msg_pk):
    msg = get_object_or_404(Message, id=msg_pk)

    msg.delete()

    return redirect('blog:inbox', username=request.user.username)


@login_required
def send_friend_invitation(request, username):
    msg = None
    if request.method == 'POST':
        current_user = request.user
        other_user = get_object_or_404(User, username=username)
        if current_user != other_user:
            if not current_user.userprofile.friends.filter(pk=other_user.pk).exists() and \
               not other_user.userprofile.friends.filter(pk=current_user.pk).exists():
                metadata = {"from_user":current_user,
                            "to_user":other_user}
                html_content = render_to_string('blog/registration/invitation_msg.html',
                                                {'meta_data': metadata})

                invitation = Message(
                    from_user=current_user,
                    to_user=other_user,
                    body=html_content,
                    seen=False,
                    subject="Someone sent you invitation!"
                )
                invitation.send()

                msg = "Friend request send!"
            else:
                msg = "You are already friends!"
        else:
            msg = "You cannot add yourself as a friend!"

    return render(request, 'blog/registration/friend_added_sucessfully.html',
                  {
                      "msg": msg
                  })


def send_message(request, username):
    messages = []
    to_user = get_object_or_404(User, username=username)
    from_user = request.user

    msg = Message(
        to_user=to_user,
        from_user=from_user)

    if request.method == "POST":
        form = SendMessageForm(request.POST, instance=msg)
        if form.is_valid():
            msg = form.save(commit=False)
            msg.send()
            return redirect('blog:profile', from_user.username)
        else:
            messages.append("An error occurred while processing the form. "
                            "Please check the entered data and try again.")
            return render(request, "blog/registration/send_message.html",

BlogDjango/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Django Girls blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <header class="page-header bg-light py-4">
    <div class="container">
        {% if user.is_authenticated %}
        <div class="d-flex align-items-center justify-content-between">
            <div>
                <p class="text-primary mb-0">Welcome, {{ user.username }}</p>
            </div>
            <div>
                <a href="{% url 'blog:post_new' %}" class="btn btn-primary me-2">
                    <i class="bi bi-plus"></i> New Post
                </a>
                <a href="{% url 'blog:profile' user.username %}" class="btn btn-secondary me-2">My Account</a>
                <a href="{% url 'blog:users' %}" class="btn btn-secondary me-2">Users</a>
                <a href="{% url 'blog:logout' %}" class="btn btn-danger">Logout</a>
            </div>
        </div>
        {% else %}
        <div class="d-flex justify-content-end">
            <a href="{% url 'blog:login' %}" class="btn btn-primary me-2">Login</a>
            <a href="{% url 'blog:register' %}" class="btn btn-secondary me-2">Register</a>
            <a href="{% url 'admin:index' %}" class="btn btn-secondary">Admin Page</a>
        </div>
        {% endif %}
        <h1 class="mt-3"><a href="/" class="text-decoration-none">Django Girls Blog</a></h1>
    </div>
</header>

    <main class="content container mt-4">
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

BlogDjango/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <article class="post">
            <div class="row">
                <div class="col-md-8">
                    <h2>{{ post.title }}</h2>
                    <p>{{ post.text|linebreaksbr }}</p>
                </div>
                <div class="col-md-4">
                    <aside class="actions">
                        {% if user.is_authenticated and post.author == user %}
                            <a class="btn btn-secondary" href="{% url 'blog:post_edit' pk=post.pk %}">
                                Edit <i class="fas fa-pencil-alt"></i>
                            </a>
                        {% endif %}
                        <a class="btn btn-secondary" href="{% url 'blog:profile' username=post.author.username %}">
                            Author: {{ post.author.username }}
                        </a>
                    </aside>
                    <time class="date">{{ post.published_date }}</time>
                </div>
            </div>
        </article>
    </div>
{% endblock %}

BlogDjango/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
        <h2>New post</h2>
        <form method="POST" class="post-form">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

BlogDjango/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="row">
        {% for post in posts %}
            <div class="col-md-6 mb-4">
                <div class="card">
                    <div class="card-body">
                        <time class="date text-muted">{{ post.published_date }}</time>
                        <h2 class="card-title"><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
                        <p class="card-text">{{ post.text|linebreaks }}</p>
                        <a href="{% url 'blog:profile' username=post.author.username %}" class="card-link">Author: {{ post.author }}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}